### ISSUE TITLE
rhn directory needs to be included in project

### ISSUE THREAD

**Issue by bschonec** [Djelibeybi/oraclelinux-reposync#12]
When running the docker image, the docker run command expects $[PWD/rhn ](https://github.com/Djelibeybi/oraclelinux-reposync/blob/32528b8e61138a6727f319e3240a05003a9a0cf3/README.md?plain=1#L30) directory to exist so that it can be 'mounted' to local directory, /etc/sysconfig/rhn.

```
example@example:~/oraclelinux-reposync$ docker run --rm -it   --name ol-repo-sync-register   -v "$PWD/rhn:/etc/sysconfig/rhn"   -v "$PWD/config:/config"   ghcr.io/djelibeybi/ol-repo-sync register
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull ghcr.io/djelibeybi/ol-repo-sync:latest...
Getting image source signatures
Copying blob 7b64ae747b04 done  
Copying blob 57cc5e862c6c done  
Copying blob f437fe6e9959 done  
Copying blob e18bf23658ab done  
Copying blob b82f6d36b890 done  
Copying config d160715ead done  
Writing manifest to image destination
Storing signatures
Error: statfs /home/example/oraclelinux-reposync/rhn: no such file or directory
```

**Comment by Djelibeybi** [comment]
If you map using `-v` then it has to exist, yes. If you don't map it, it will be created inside the container and essentially ignored. It has to exist prior to the container starting if you want ULN connectivity because it has to be able to save the ULN configuration externally.

Edited to add that this is documented in the requirements in the README.md

**Comment by bschonec** [comment]
This doesn't solve the issue.  As shown above, docker errors out when ./rhn doesn't exist.

`Error: statfs /home/example/oraclelinux-reposync/rhn: no such file or directory`

It doesn't hurt to have the rhn directory in the project.  If the user wants to use ULN, then the rhn directory needs to be created manually.  The README doesn't make it clear NOT to include the -v $PWD/rhn parameter when you don't register with ULN.  The documentation should be updated to reflect this behavior or a section added to the README that shows the correct docker command usage that doesn't include the mapping to ./rhn.

**Comment by Djelibeybi** [comment]
Remove `-v "$PWD/rhn:/etc/sysconfig/rhn"` from your command if you're not using it. It's erroring out because you're telling Docker that `$PWD/rhn` exists when it doesn't.

**Comment by bschonec** [comment]
Yes, I realize that but the documentation should reflect this behavior.   All of the examples assume that the user is using ULN and if he is, then he needs to create $PWD/rhn manually.  Why make it more difficult for the user?  ./rhn should be included in the project.  If you need it, rhn is there.  If you don't, rhn will be ignored.
