### ISSUE TITLE
uln repos not added to config/repo-map.json

### ISSUE THREAD

**Issue by twau** [Djelibeybi/oraclelinux-reposync#14]
Hi

Thanks for this awesome container image!

I have followed the instructions and only the yum.oracle.com repos is added to the repo-map.json, not any of the uln repos that I have added to my repos.json file, is this the way it should be?
I am trying to only mirror uln repos, for example I have added ol7_x86_64_userspace_ksplice as an test to repos.json

```
# cat repos.json
{
    "uln": [
        "ol7_x86_64_userspace_ksplice"
    ]
}
```
If I then run ol-repo-sync update repo-map.json is not updated with ol7_x86_64_userspace_ksplice. If I then try to sync it is downloaded but not saved in /repo since the "${REPOPATH}" is not set cause it is missing in the repo-map.json file.

However if I manually edit repo-map.json with below, it works.
```
    {
            "baseurl": "/repo/OracleLinux/OL7/ol7_x86_64_userspace_ksplice",
            "label": "ol7_x86_64_userspace_ksplice"
    }
```
Is this by design or is it something that is broken?

**Comment by Djelibeybi** [comment]
There are some repos (like Ksplice and the Java SE ones) that don't exist on yum.oracle.com so cannot bec automatically mapped. Doing it manually like you did is exactly the right thing to do. 

On that note, keep in mind that the Ksplice repos are _HUGE_. We're talking multiple terabytes. If you run `dnf repolist -v` it should show you the current size on ULN. Remember the repo will _never_ get smaller.
